from pinkhat.iacparsers.utils.graph_db.graph_schema.enum_table_name import TableName

BODY_RELATIONSHIPS = [
    TableName.AnnAssign.value,
    TableName.Assign.value,
    TableName.Assert.value,
    TableName.Attribute.value,
    TableName.AsyncFunctionDef.value,
    TableName.AsyncWith.value,
    TableName.AugAssign.value,
    TableName.Break.value,
    TableName.Call.value,
    TableName.ClassDef.value,
    TableName.Constant.value,
    TableName.Continue.value,
    TableName.Delete.value,
    TableName.Dict.value,
    TableName.Expr.value,
    TableName.For.value,
    TableName.FunctionDef.value,
    TableName.Global.value,
    TableName.If.value,
    TableName.IfExp.value,
    TableName.Import.value,
    TableName.ImportFrom.value,
    TableName.Lambda.value,
    TableName.List.value,
    TableName.Name.value,
    TableName.Pass.value,
    TableName.Try.value,
    TableName.Raise.value,
    TableName.Return.value,
    TableName.While.value,
    TableName.With.value,
]
